export let pets = [
    {
      "name": "Milo",
      "id": "x000001",
      "img": "assets/Images/milo.jpg",
      "alt": "A curious and affectionate 2-year-old Siamese cat",
      "type": "Cat",
      "breed": "Siamese",
      "description": "Milo is a curious and affectionate 2-year-old Siamese. He loves to explore his surroundings and enjoys curling up in your lap for a nap. Milo is a social cat who gets along well with other pets.",
      "age": "2 years",
      "inoculations": ["rabies", "feline leukemia"],
      "diseases": ["none"],
      "parasites": ["none"]
    },
    {
      "name": "Bella",
      "id": "x000002",
      "img": "assets/Images/bella.jpg",
      "alt": "A playful and friendly 4-year-old Labrador",
      "type": "Dog",
      "breed": "Labrador Retriever",
      "description": "Bella is a playful and friendly 4-year-old Labrador. She is full of energy and loves to play fetch. Bella is looking for an active family that can keep up with her playful nature.",
      "age": "4 years",
      "inoculations": ["parvovirus", "canine influenza"],
      "diseases": ["none"],
      "parasites": ["fleas"]
    },
    {
      "name": "Oliver",
      "id": "x000003",
      "img": "assets/Images/oliver.jpg",
      "alt": "A gentle giant Maine Coon at 5 years old",
      "type": "Cat",
      "breed": "Maine Coon",
      "description": "Oliver is a gentle giant at 5 years old. He is calm and enjoys lounging around the house. Oliver is a perfect companion for someone looking for a low-maintenance, affectionate pet.",
      "age": "5 years",
      "inoculations": ["feline distemper", "rabies"],
      "diseases": ["none"],
      "parasites": ["ear mites"]
    },
    {
      "name": "Charlie",
      "id": "x000004",
      "img": "assets/Images/charlie.jpg",
      "alt": "A 1-year-old Beagle who is full of life",
      "type": "Dog",
      "breed": "Beagle",
      "description": "Charlie is a 1-year-old Beagle who is full of life. He loves to sniff around and explore new places. Charlie is great with kids and other dogs, making him a wonderful addition to any family.",
      "age": "1 year",
      "inoculations": ["bordetella", "leptospirosis"],
      "diseases": ["none"],
      "parasites": ["none"]
    },
    {
      "name": "Luna",
      "id": "x000005",
      "img": "assets/Images/luna.jpg",
      "alt": "A 3-year-old Bengal cat with a lot of personality",
      "type": "Cat",
      "breed": "Bengal",
      "description": "Luna is a 3-year-old Bengal with a lot of personality. She is active, loves to climb, and needs a home where she can have plenty of stimulation. Luna is also very affectionate and enjoys being around people.",
      "age": "3 years",
      "inoculations": ["feline leukemia", "calicivirus"],
      "diseases": ["none"],
      "parasites": ["none"]
    },
    {
      "name": "Max",
      "id": "x000006",
      "img": "assets/Images/max.jpg",
      "alt": "A loyal and protective 6-year-old German Shepherd",
      "type": "Dog",
      "breed": "German Shepherd",
      "description": "Max is a loyal and protective 6-year-old German Shepherd. He has been trained in basic commands and is very obedient. Max would thrive in a home where he has a job to do or a lot of space to run.",
      "age": "6 years",
      "inoculations": ["rabies", "parainfluenza"],
      "diseases": ["hip dysplasia"],
      "parasites": ["none"]
    },
    {
      "name": "Daisy",
      "id": "x000007",
      "img": "assets/Images/daisy.jpg",
      "alt": "A 4-year-old Persian cat with a calm and relaxed demeanor",
      "type": "Cat",
      "breed": "Persian",
      "description": "Daisy is a 4-year-old Persian with a calm and relaxed demeanor. She loves to be pampered and enjoys quiet environments. Daisy is the perfect pet for someone who appreciates the finer things in life.",
      "age": "4 years",
      "inoculations": ["rabies", "feline rhinotracheitis"],
      "diseases": ["none"],
      "parasites": ["none"]
    },
    {
      "name": "Buddy",
      "id": "x000008",
      "img": "assets/Images/buddy.jpg",
      "alt": "A 2-year-old Cocker Spaniel with a friendly and cheerful disposition",
      "type": "Dog",
      "breed": "Cocker Spaniel",
      "description": "Buddy is a 2-year-old Cocker Spaniel with a friendly and cheerful disposition. He loves to be around people and is always ready for a game of fetch or a walk in the park. Buddy is looking for a loving home.",
      "age": "2 years",
      "inoculations": ["distemper", "parvovirus"],
      "diseases": ["none"],
      "parasites": ["fleas"]
    }
  ];